  {
	    	if (SceneUV.x >= 0.5 - CROSSHAIR_CROSS_SIZE && SceneUV.x <= 0.5 + CROSSHAIR_CROSS_SIZE && SceneUV.y >= 0.499 && SceneUV.y <= 0.501)
        	{
        		OutColor =  CROSSHAIR_CROSS_COLOR;
        	}
        	else if (SceneUV.x >= 0.4995 && SceneUV.x <= 0.5005 && SceneUV.y >= 0.5 - (CROSSHAIR_CROSS_SIZE * aspectRatio) && SceneUV.y <= 0.5 + (CROSSHAIR_CROSS_SIZE * aspectRatio))
        	{
        		OutColor =  CROSSHAIR_CROSS_COLOR;
        	}
        }